development: &defaults
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: kickmapper_development
  username: kickmapper
  password: fUtr4spAcA

test:
  <<: *defaults
  database: kickmapper_test

production:
  <<: *defaults
  database: kickmapper_production
